name: diario_emocional
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.7.2
  sqflite: ^2.4.2
  path: ^1.9.1
  intl: ^0.20.2
  http: ^1.4.0
  table_calendar: ^3.2.0
  flutter_dotenv: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0

flutter:
  uses-material-design: true
  assets:
    - .env
  fonts:
    - family: Fredoka
      fonts:
        - asset: assets/fonts/Fredoka/Fredoka-Regular.ttf
        - asset: assets/fonts/Fredoka/Fredoka-Medium.ttf
          weight: 500
        - asset: assets/fonts/Fredoka/Fredoka-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Fredoka/Fredoka-Bold.ttf
          weight: 700

    - family: FredokaCondensed
      fonts:
        - asset: assets/fonts/Fredoka/Fredoka_Condensed-Regular.ttf
        - asset: assets/fonts/Fredoka/Fredoka_Condensed-Medium.ttf
          weight: 500
        - asset: assets/fonts/Fredoka/Fredoka_Condensed-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Fredoka/Fredoka_Condensed-Bold.ttf
          weight: 700

    - family: FredokaExpanded
      fonts:
        - asset: assets/fonts/Fredoka/Fredoka_Expanded-Regular.ttf
        - asset: assets/fonts/Fredoka/Fredoka_Expanded-Medium.ttf
          weight: 500
        - asset: assets/fonts/Fredoka/Fredoka_Expanded-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Fredoka/Fredoka_Expanded-Bold.ttf
          weight: 700

flutter_native_splash:
  color: "#ffffff"
  image: assets/icon/app_icon.png
  android_gravity: center
  android: true

flutter_icons:
  android: true
  image_path: "assets/icon/app_icon.png"